# Generated by Django 3.0.8 on 2020-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('deposit_date', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('cp', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('cp', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
            ],
        ),
    ]
