# Generated by Django 3.0.5 on 2020-07-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leboncoin', '0002_auto_20200725_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=1000)),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('vendeur_nom', models.CharField(max_length=120)),
                ('vendeur_telephone', models.CharField(max_length=20)),
                ('vendeur_ville', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
